<a href="https://colab.research.google.com/github/pharringtonp19/business-analytics/blob/main/notebooks/regression/interpretation_categorical_variables.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!git clone https://github.com/pharringtonp19/business-analytics.git

Cloning into 'business-analytics'...
remote: Enumerating objects: 1289, done.
remote: Counting objects: 100% (344/344), done.
remote: Compressing objects: 100% (90/90), done.
remote: Total 1289 (delta 316), reused 254 (delta 254), pack-reused 945 (from 1)
Receiving objects: 100% (1289/1289), 21.86 MiB | 12.57 MiB/s, done.
Resolving deltas: 100% (772/772), done.

### **Import Packages**

In [2]:
import pandas as pd
pd.set_option('display.max_columns', None)
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import statsmodels.formula.api as smf
from statsmodels.iolib.summary2 import summary_col
import plotly.graph_objects as go
import plotly.express as px
import numpy as np
import jax.numpy as jnp
import jax
import seaborn as sb
from functools import partial

### **Read In Data Set**

In [5]:
df = pd.read_csv('/content/business-analytics/datasets/sodaSales.csv')
df.head()

,store,population,income,education,cost,competition,price,units_sold,promotion
0,1,2265,57.87,37,0.80,1,2.25,1018,B
1,2,2999,30.03,7,0.39,1,1.00,600,NONE
2,3,2579,60.30,34,0.64,1,1.75,2330,B
3,4,3766,48.11,44,0.95,1,3.00,2225,B
4,5,1560,40.42,22,0.69,0,1.75,593,NONE

### **Value Counts of Control Variables**

In [10]:
df['promotion'].value_counts()

promotion
B       256
NONE    176
A        64
Name: count, dtype: int64

### **Estimate Model**

In [11]:
linear_model = smf.ols('units_sold ~ promotion', data=df)
results = linear_model.fit()
results.params

Intercept            1171.937500
promotion[T.B]         87.511719
promotion[T.NONE]    -196.801136
dtype: float64